
# From https://hub.docker.com/r/mysql/mysql-server

# Create mysql docker image
docker pull mysql/mysql-server
docker run --name=mysqldev -p 5306:3306-d mysql/mysql-server

# Get autogenerated password
docker logs mysqldev 2>&1 | grep GENERATED

# Create the database, user etc
docker exec -it mysqldev mysql -uroot -p --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'netr00t'";
docker exec -it mysqldev mysql -uroot -pnetr00t -e "CREATE DATABASE dfweb"
docker exec -it mysqldev mysql -uroot -pnetr00t -e "CREATE USER 'dfweb'@'%' IDENTIFIED BY 'testpass';"
docker exec -it mysqldev mysql -uroot -pnetr00t -e "GRANT ALL PRIVILEGES ON * . * TO 'dfweb'@'%';"
docker exec -i mysqldev mysql -uroot -pnetr00t dfweb < ../../../ExternalTools/Data/darkfactorweb.sql