version: '3.6'
services:
  dfweb:
    build:
      network: host
      context: ./
      dockerfile: ./DarkFactorWeb/Dockerfile
    ports:
      - "8080:80"

  database:
    image: mysql/mysql-server:8.0.17
    user: root
    environment:
    - "MYSQL_ROOT_PASSWORD=secret"
    - "MYSQL_DATABASE=dfweb"
    - "MYSQL_USER=webuser"
    - "MYSQL_PASSWORD=secretpwd"
    volumes:
    - darkfactorweb-mysqldb:/var/lib/mysql
    #- ./MySqlServer/my.cnf:/etc/my.cnf
    - ./MySqlServer/darkfactorweb.sql:/darkfactorweb.sql
    ports:
    - "5306:3306"
  
volumes:
  darkfactorweb-mysqldb:
    external: true