version: '3.6'
services:
  webapp:
    build:
      network: host
      context: ./
      dockerfile: ./DarkFactorWeb/Dockerfile
    ports:
      - "8080:80"

  database:
    image: mariadb
    user: root
    environment:
    - "MYSQL_ROOT_PASSWORD=secret"
    - "MYSQL_DATABASE=dfweb"
    - "MYSQL_USER=webuser"
    - "MYSQL_PASSWORD=secretpwd"
    volumes:
    - webapp-mariadb:/var/lib/mysql
    - ./database/my.cnf:/etc/my.cnf
    ports:
    - "3306:3306"
  
volumes:
  webapp-mariadb:
    external: true