version: '3.6'
services:

  dfwebadmin:
    container_name: darkfactorweb_adminer
    image: adminer
    restart: always
    networks: 
      - net_dfweb_backend
    environment: 
      ADMINER_DEFAULT_SERVER: dfwebdb
    ports:
      - 4001:8080

  dfwebdb:
    image: mariadb:10.9
    container_name: darkfactorweb_database
    user: root
    restart: always
    networks: 
      - net_dfweb_backend
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=dfweb"
      - "MYSQL_USER=webuser"
      - "MYSQL_PASSWORD=secretpwd"
    volumes:
      - darkfactorweb-mariadb:/var/lib/mysql
      - ./database/darkfactorweb.sql:/darkfactorweb.sql
      #- ./database/createdb.sql:/createdb.sql
      #- ./database/my.cnf:/etc/my.cnf
    ports:
      - 4002:3306

  dfweb:
    container_name: darkfactorweb_web
    build:
      network: host
      context: ./
      dockerfile: ./DarkFactorWeb/Dockerfile
      args:
        username: ${NUGET_USERNAME}
        token: ${NUGET_TOKEN}
    ports:
      - "4000:80"
    networks:
      - net_dfweb_backend

    depends_on: 
      - dfwebdb

networks:
  net_dfweb_backend:
    name: dfweb_backend

volumes:
  # docker volume create darkfactorweb-mariadb
  darkfactorweb-mariadb:
    external: true  